export const environment = {
  production: false,
  apiBaseUrl: 'http://127.0.0.1:8000/api/',
  toastDuration: 2000,
  activation: {
    successDelay: 2500,
    errorDelay: 3000,
  },
  hls: {
    maxBufferLength: 45,
    maxMaxBufferLength: 900,
    maxBufferSize: 90 * 1000 * 1000,
    maxBufferHole: 0.5,
    backBufferLength: 90,
    lowBufferWatchdogPeriod: 0.5,
    highBufferWatchdogPeriod: 2,
    nudgeOffset: 0.1,
    nudgeMaxRetry: 3,
    maxFragLookUpTolerance: 0.25,
    enableWorker: true,
    startFragPrefetch: true,
    testBandwidth: true,
    enableSoftwareAES: true,
    maxSeekHole: 2,
    seekHoleNudgeDuration: 0.01,
    manifestLoadingTimeOut: 10000,
    manifestLoadingMaxRetry: 4,
    levelLoadingTimeOut: 10000,
    levelLoadingMaxRetry: 4,
    fragLoadingTimeOut: 20000,
    fragLoadingMaxRetry: 6,
    appendErrorMaxRetry: 3,
    loaderMaxRetry: 2,
    loaderMaxRetryTimeout: 64000,
    lowLatencyMode: false,
    enableCEA708Captions: false,
    stretchShortVideoTrack: false,
    forceKeyFrameOnDiscontinuity: true,
    liveSyncDurationCount: 3,
    liveMaxLatencyDurationCount: 10,
    liveDurationInfinity: false,
    maxAudioFramesDrift: 1,
    maxVideoFramesDrift: 1,
    debug: false,
    enableDateRangeMetadataCues: false,
    enableEmsgMetadataCues: false,
    enableID3MetadataCues: false,
  },
};
